#!/bin/sh
[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
[ -s ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
export root="${IPKG_INSTROOT}"
export pkgname="uhttpd-mod-ubus"
add_group_and_user
default_postinst
#!/bin/sh
if [ -z "${IPKG_INSTROOT}" ]; then
	/etc/init.d/uhttpd reload
fi
